#!/usr/bin/env bash
#PBS -l nodes=2:ppn=1
#PBS -W x=nmatchpolicy:exactnode
#PBS -l pmem=300mb
#PBS -l qos=debugging
#PBS -l walltime=00:05:00
#PBS -j oe

cd $PBS_O_WORKDIR
source switch_to_2015a
module load intel

export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=disable
export OMP_NUM_THREADS=2
export OMP_PROC_BIND=true

mpirun --np 2 --ppn 1 -genv I_MPI_PIN_DOMAIN=omp:compact \
    ./mem_limit -f conf/cgroups_works.conf -l 10s

